[package]
name = "text-embedding-inference"
version = "0.0.1"
edition = "2024"

[dependencies]
candle-core = "0.9.1"
anyhow = "1.0"
tokenizers = "0.21.4"
turso = "0.1.3"
tokio = { version = "1.0", features = ["full"] }